spring:
  application.name: user
  cloud.kubernetes.reload.enabled: true
server.port: 8080
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
ribbon:
  http:
    client:
      enabled: true