---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: main-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: main
  replicas: 1
  template:
    metadata:
      labels:
        app: main
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      initContainers:
        - name: init-redis
          image: busybox:1.28.4
          command: ['sh', '-c', 'until nslookup redis.default.svc.cluster.local; do echo waiting for redis; sleep 2; done;']
        - name: init-base
          image: busybox:1.28.4
          command: ['sh', '-c', 'until nslookup base-service.default.svc.cluster.local; do echo waiting for base-service; sleep 2; done;']
      containers:
        - name: main
          image: kubescaler/main:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              cpu: 0.5
              memory: 512Mi
