apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: main-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
