---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stream-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: stream
  replicas: 1
  template:
    metadata:
      labels:
        app: stream
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      initContainers:
        - name: init-redis
          image: busybox:1.28.4
          command: ['sh', '-c', 'until nslookup redis.default.svc.cluster.local; do echo waiting for redis; sleep 2; done;']
        - name: init-base
          image: busybox:1.28.4
          command: ['sh', '-c', 'until nslookup base-service.default.svc.cluster.local; do echo waiting for redis; sleep 2; done;']
      containers:
        - name: stream
          image: kubescaler/stream:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              cpu: 1
              memory: 512Mi
