---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: base-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: base
  replicas: 1
  template:
    metadata:
      labels:
        app: base
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      initContainers:
        - name: init-cassandra
          image: busybox:1.28.4
          command: ['sh', '-c', 'until nslookup cassandra.default.svc.cluster.local; do echo waiting for cassandra; sleep 2; done;']
      containers:
        - name: base
          image: kubescaler/base:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              memory: 512Mi
