apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  backend:
    serviceName: main-service
    servicePort: 8080
#  rules:
#    - http:
#        paths:
#          - path: /testpath
#            backend:
#              serviceName: test
#              servicePort: 80