FROM adoptopenjdk/openjdk12:alpine-slim
VOLUME /tmp
COPY target/base-1.0-SNAPSHOT.jar app.jar
ENV JAVA_OPTS=""
ENTRYPOINT exec java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9999 -jar /app.jar