apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: processor-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: processor-deployment
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
