---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-deployment
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template:
    metadata:
      labels:
        app: user
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      initContainers:
        - name: init-cassandra
          image: busybox:1.28.4
          command: ['sh', '-c', 'until nslookup cassandra; do echo waiting for cassandra; sleep 2; done;']
        - name: init-redis
          image: busybox:1.28.4
          command: ['sh', '-c', 'until nslookup redis; do echo waiting for redis; sleep 2; done;']
      containers:
        - name: user
          image: kubescaler/user:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              memory: 512Mi
