---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-deployment
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template:
    metadata:
      labels:
        app: user
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: user
          image: user:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              memory: 256Mi
